services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: eval_admin
      POSTGRES_PASSWORD: eval_password_123
      POSTGRES_DB: eval_platform
    ports:
      - "5544:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: